AllCops:
  Include:
    - '**/Rakefile'
    - '**/*.task'
    - '**/*.rake'
    - '**/*.rb'
  Exclude:
    - 'config/**/*'
    - 'db/**/*'
    - 'doc/**/*'
    - 'features/**/*'
    - 'log/**/*'
    - 'public/**/*'
    - 'script/**/*'
    - 'test/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'

require: rubocop-rspec

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 3

RSpec/ExampleLength:
  Enabled: false

Layout/LineLength:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
